### ISSUE TITLE
won't build

### ISSUE THREAD

**Issue by fluidvoice** [KamilLelonek/ex_wallet#2]
fails to build for me..

Makefile.am: installing 'build-aux/depcomp'
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... cc
checking whether the C compiler works... no
configure: error: in `/home/brad/working/elixir/bitcoin/ex_wallet/deps/libsecp256k1/c_src/secp256k1':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: Command [compile] failed!
** (Mix) Could not compile dependency :libsecp256k1, "/home/brad/.mix/rebar compile skip_deps=true deps_dir="/home/brad/working/elixir/bitcoin/ex_wallet/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"

**Comment by fluidvoice** [comment]
Erlang/OTP 21 [erts-10.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Mix 1.6.6 (compiled with OTP 21)

**Comment by fluidvoice** [comment]
$ sudo mix deps.compile libsecp256k1
==> libsecp256k1 (compile)
HEAD is now at 5a91bd7 Merge #400: A couple minor cleanups
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... cc
checking whether the C compiler works... no
configure: error: in `/home/brad/working/elixir/bitcoin/ex_wallet/deps/libsecp256k1/c_src/secp256k1':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: Command [compile] failed!
** (Mix) Could not compile dependency :libsecp256k1, "/root/.mix/rebar compile skip_deps=true deps_dir="/home/brad/working/elixir/bitcoin/ex_wallet/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"

**Comment by fluidvoice** [comment]
[brad@G50 ex_wallet]$ gcc --version
gcc (GCC) 8.1.1 20180531

**Comment by fluidvoice** [comment]
.config.log shows...

configure:3541: checking whether the C compiler works
configure:3563: cc    -lstdc++ conftest.c  >&5
cc: internal compiler error: Segmentation fault signal terminated program cc1
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.

**Comment by fluidvoice** [comment]
I removed and reinstalled GCC, now it gets farther in the build but still fails...
>$ sudo mix deps.compile libsecp256k1

... stuff omitted...
config.status: creating Makefile
config.status: creating libsecp256k1.pc
config.status: creating src/libsecp256k1-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
  CC       src/tests-tests.o
src/tests.c: In function ‘test_ecdsa_der_parse’:
src/tests.c:3702:52: error: dereferencing pointer to incomplete type ‘ECDSA_SIG’ {aka ‘struct ECDSA_SIG_st’}
         valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                    ^~
make: *** [Makefile:1044: src/tests-tests.o] Error 1
ERROR: Command [compile] failed!
** (Mix) Could not compile dependency :libsecp256k1, "/root/.mix/rebar compile skip_deps=true deps_dir="/home/brad/working/elixir/bitcoin/ex_wallet/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"

**Comment by KamilLelonek** [comment]
What is your OS?

**Comment by fluidvoice** [comment]
Manjaro Xfce 17.1.12 kernel 4.14.63

**Comment by KamilLelonek** [comment]
OMG, that's why I use MacOS 😅

**Comment by KamilLelonek** [comment]
Can you do sth like https://github.com/KamilLelonek/ex_wallet#prerequisites on your system?

**Comment by fluidvoice** [comment]
It's the #1 most popular Linux distribution!  well, if you exclude Mac and Android.
https://distrowatch.com

**Comment by arruah** [comment]
On my Ubuntu 18.04 everything is ok.

**Comment by KamilLelonek** [comment]
Closing then.
